- pages/docs/roadmap/release-notes.md
Fixes an error where the DS Pipelines version was incorrectly updated to 1.3.1
Closes #55 
> Fix DS Pipelines version in the release notes

- pages/docs/getting-started/beta/quick-installation.md
- pages/docs/modules/troubleshooting-common-problems-in-jupyter-for-users.adoc
I have changed the "next" link after Getting started to link the new pages [Data Science Projects](https://opendatahub.io/docs/working-on-data-science-projects.html) and update the [Data Science Projects](https://opendatahub.io/docs/working-on-data-science-projects.html) and add the "next" page [Administration](https://opendatahub.io/docs/administration/installation-customization/customization.html).
Closes #61
> Fix Adminstration link on Documentation after Getting Started #61

- src/content/blog/2023-04-06-odh-release-1.5.0-blog.md
- src/content/blog/2023-05-15-odh-release-1.6.0-blog.md
Adds the release blogs for the ODH 1.5 and 1.6 releases to the new odh.io redesign
> Add release blogs for ODH 1.5 and 1.6

- src/components/pages/home/CommunityDetails.tsx
Update the `Mailing List` to default to announcements@lists.opendatahub.io as the only choice for interested users
> Use announcements@list.opendatahub as the only mailing list

- src/content/docs/release-notes.md
Adds the ODH v1.6.0 release to the release notes and links each release header to the the corresponding blog for streamline navigation to the detailed release notes
> Add ODH v1.6.0 release notes

- src/content/docs/quick-installation.md
The links on https://opendatahub.io/docs/quick-installation/ to `ODH Core components` result in a 404 as the url is
`https://opendatahub.io/docs/docs/tiered-components.html` and `https://opendatahub.io/docs/quick-installation/%7B%7Bsite.baseurl%7D%7D/docs/tiered-components.html` instead of `https://opendatahub.io/docs/tiered-components`
Ran it locally, checked the links
> Fix broken links to tiered components page

- src/content/docs/quick-installation.md
Fixes the issues in the quick installation docs where the markdown was not parsing the numbered lists as combined list with sequential numbering.  Markdown was resetting each list item back to `1.` due to the image link not being parented under the list item with indentation
Local deployment to confirm the change works
Markdown changes work as expected
> Fix markdown list numbering in the quick-installation docs

- src/content/blog/2023-06-28-odh-release-1.7.0-blog.md
Fixes an invalid link to the incubation notebooks blog in the ODH 1.7 release notes
> Fix incorrect link in 1.7.0 blog to incubation notebook blog

- src/content/blog/2023-08-12-odh-release-1.9.0-blog.md
Update the ODH v1.9.0 announcement to remove the redundant notable changes. Add a reminder to users about the alpha release of odh-operator v2.x
> Update odh 1.9.0 announcement with odh-operator v2.0 note

- src/content/docs/quick-installation-new-operator.md
Tweak the guidance a bit to match the 2.1.0 behaviour when some components are selected by default.
https://github.com/opendatahub-io/opendatahub.io/issues/186
No testing was done.
> Some components are enabled by default.

- src/content/docs/quick-installation.md
Clarify that the odh namespace is only needed when the instance is being created, not for the operator installation.
The order of the steps was all over the place, it also caused the `odh` namespace being created even if installing the 2.X operator (where per https://opendatahub.io/docs/quick-installation-new-operator/ it is not used at all).
Not tested.
> Clarify that the odh namespace is only needed when the instance is being created

- src/content/blog/2023-07-24-odh-operator-v2.0-blog.md
> Update DSC Blog to refer v1 api

- src/components/pages/home/CompetitiveAdvantage.tsx
The home page is missing space after comma, even if the source has a newline there.
```
host$ podman run --rm -ti registry.fedoraproject.org/fedora
container# dnf install -y npm git-core g++ patch
container# git clone https://github.com/opendatahub-io/opendatahub.io.git
container# cd opendatahub.io/
container# npm ci
container# npm run build
container# grep -r 'to orchestrate workflows,<span' public
container# grep -r 'to orchestrate workflows, <span' public
container# patch -p1
container# npm run build
container# grep -r 'to orchestrate workflows,<span' public
container# grep -r 'to orchestrate workflows, <span' public
```
Without the patch, the grep without space after comma outputs a looong line.
With the patch, the grep with space after comma outputs a looong line.
> Workaround gatsby/something stripping space before the <span> element

- src/const.ts
- src/templates/docs-page.tsx
Updated the Open Data Hub doc's left navigation bar to:
- Include two new guides "Monitoring data science models" and "Monitoring performance metrics"
- Include level 2 headings
> ds-docs-navbar-update

- src/const.ts
removing "Monitoring performance metrics" from the left navbar -
added doc prematurely - this feature not yet in the ODH UI
> ds-docs-navbar-edit

- gatsby-config.ts
Move to release-based documentation builds.
> Update gatsby-config.ts to reference v2.4 documentation release tag

- gatsby-config.ts
Update `gatsby-config.ts` to point docs to the 2.5 release tag in https://github.com/opendatahub-io/opendatahub-documentation.
> Update docs to 2.5 release tag

- gatsby-config.ts
Update `gatsby-config.ts` to point docs to the `2.5.1` release tag in https://github.com/opendatahub-io/opendatahub-documentation.
> Update docs to 2.5.1 release tag

- src/const.ts
Add model serving guide to left navigation menu.
Tested with local build of the ODH site.
> Add model-serving guide to left navigation menu

- gatsby-config.ts
Point to 2.6.1 documentation release to pick up a handful of minor post-2.6 updates.
> Point docs to 2.6.1 documentation release

- gatsby-config.ts
Point docs build to `v2.8` release tag.
> Point to documentation for 2.8 release

- gatsby-config.ts
Point docs build to `v2.9` release tag.
> Point to documentation for 2.9 release

- src/const.ts
Setting links back to use hyphens instead of underscores to avoid breaking other links
> changing links back to use hyphens

- gatsby-config.ts
The v2.11 opendatahub-documentation release is available. This PR points to it.
> Point to documentation for 2.11 release

- src/const.ts
updated the ODH Doc table of contents to include two new titles (reorganized existing content)- for v2.11
- Working with data science pipelines
- Working in your data science IDE
Tested opendatahub.io build locally - verified in local build (http://localhost:9000/) that this edit update the TOC as expected
> odh-update-doc-toc

- src/templates/docs-page.tsx
Provide a message to users about the latest release notes.
After some discussion with the team, it seems that the information about a release should have a singe source of truth and that being the https://github.com/opendatahub-io/opendatahub-operator/releases/latest.
So the idea is to provide a useful notice to the users so that they can navigate to the correct one.
> Add an alert to point users to the correct relese notes.

- gatsby-config.ts
Updates gatsby-config.ts to point to the latest release tag for the ODH docs updates that correspond to RHOAI 2.16.
> Point to docs changes for 2.16 release.

- gatsby-config.ts
Updates gatsby-config.ts to point to the v2.18 branch for the ODH docs updates that correspond to RHOAI 2.18.
> Point to documentation for 2.18 release

- gatsby-config.ts
Updates gatsby-config.ts to point to the latest docs branch: https://github.com/opendatahub-io/opendatahub-documentation/tree/v2.19
> [ccs] Point to docs branch for 2.19 release.
