opendatahub-io/opendatahub.io

_posts/2021-02-02-odh-release-1.0.0-blog.md
=> Fix incorrect link and version

_posts/2021-07-13-odh-release-1.1.0-blog.md
Adding Release notes for ODH v 1.1.0
=> Adding ODH 1.1.0 release notes

_data/roadmap.yml
This includes all the updates for ODH 1.2 and 1.3 release roadmap.
=> Updating roadmap for Q4 2021 Q1 2022

_posts/2022-01-10-odh-release-1.1.1-blog.md, _posts/2022-02-09-odh-release-1.1.2-blog.md
Adds release notes for the ODH v1.1.1 and v1.1.2
=> Add release notes for odh v1.1.1 & v1.1.2

LICENSE
=> Update license from GPL to Creative Commons 4

_posts/2022-04-29-odh-release-1.2.0-blog.md
Add release news for ODH v1.2.0
=> Add release notes for odh v1.2.0

_data/roadmap.yml
BYON will not use pipelines, update roadmap to reflect this change.
=> Do not specify BYON backend technology

_posts/2022-07-20-odh-release-1.3.0-blog.md, pages/docs/roadmap/release-notes.md
Add posts for the release of ODH v1.3.0
=> Add post for the ODH v1.3.0 release

_includes/community-scripts.html, pages/community.html
=> Update community meeting calendar to use opendatahub.community account

pages/docs/introduction.md
Added Oxford comma and fixed a spelling error
=> Fix intro typo

_data/docs_toc.yml, _data/roadmap.yml, pages/docs/additional.md, pages/docs/getting-started/beta/basic-tutorial.md, pages/docs/introduction.md, pages/docs/roadmap/release-notes.md, pages/docs/tiered-components.md
Adds docs for describing the ODH component tiers and updating the architecture
N/A
No grammatical errors
Docs are rendered correctly
Information is clear
=> Add initial component tiers docs

pages/community.html
=> Add slack invite link to the community page

index.html
We should refer to Apache Kafka. I also added a link to the Kafka website as the word 'Kafka' should not be used to link to the Strimzi website.
I opened index.html in my browser and verified the links work.
=> Refer to Kafka as Apache Kafka

_posts/2023-01-24-odh-release-1.4.1-blog.md, pages/docs/roadmap/release-notes.md
Announce release of ODH 1.4.1 Release
=> ODH 1.4.1 Release

_posts/2023-01-24-odh-release-1.4.1-blog.md, pages/docs/roadmap/release-notes.md
=> Correct Notebook Images category for v1.4.1

_posts/2023-01-24-odh-release-1.4.1-blog.md
Fix spelling of jupyer to jupyter in release notes
N/A
- [N/A] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [N/A] The developer has manually tested the changes and verified that the changes work
=> fix jupyter spelling

index.html
Conducted a review of the ODH homepage and have implemented certain revisions pertaining to its punctuation.
=> punctuation and format

_posts/2023-03-14-odh-release-1.4.2-blog.md, _posts/2023-04-06-odh-release-1.5.0-blog.md
Announcement for the v1.5.0 release of Open Data Hub
=> Announce the release of ODH 1.5.0

_data/roadmap.yml, pages/docs/roadmap/release-notes.md
Update the Roadmap to include the 1.5 and 1.6 releases of ODH
=> Update roadmap for 1.5 and 1.6 release

index.d.ts, package-lock.json, package.json, src/components/pages/home/CompetitiveAdvantage.tsx, src/components/shared/Layout.tsx, src/pages/index.tsx, src/styles/theme.scss
related: https://github.com/opendatahub-io/opendatahub.io/issues/83
added comp adv ui. video by default is disabled
=> added comp advantage

src/components/pages/home/CommunityDetails.tsx, src/components/shared/GeometryBackgroundInv.css, src/components/shared/GeometryBackgroundInv.tsx, src/pages/index.tsx
Resolves: #86 
Adds the Community details component according to the mockup:
Also adds working links.
=> Add Community Details Component

src/components/pages/home/FeaturedBlogs.tsx
=> Add Featured Blogs component

gatsby-node.ts, package-lock.json, package.json
=> fixed deps

src/content/posts/2023-05-19-docs-distributedworkloads.md
=> Distributed workloads ticker

src/components/shared/ContentCard.tsx, src/pages/blog.tsx
=> feat: added search/filter to blogpage

src/components/pages/home/ArchitectureMap.tsx
Added recommended punctuation changes per review 5/22/2023
=> Changes to punctuation

src/components/pages/home/ArchitectureMap.tsx
=> removed grafana

README.md, src/components/pages/home/ArchitectureMap.tsx, src/content/blog/2022-10-31-odh-release-1.4.0-blog.md, src/templates/blog-post.tsx
=> Update the readme

src/content/docs/quick-installation.md
Fixes the broken image links on the quick installation page
=> Fix broken image links in the quick-installation docs

.github/workflows/deploy-site.yml
=> Update deploy-site.yml to deploy on main

gatsby-config.ts
=> updated google tag

gatsby-config.ts
=> added ga id

src/content/blog/2023-06-23-vscode-rstudio-incubation-blog.md
Added blog for VS Code and R Studio incubation into ODH
Closes #160
=> Add blog for Code Server(VS Code) and R Studio incubation into ODH

src/const.ts, src/content/blog/2023-06-28-odh-release-1.7.0-blog.md, src/content/docs/release-notes.md
Add the ODH 1.7 release announcement
Closes #158
Deployed locally to ensure there are no typos
Information is accurate and error free
=>  ODH 1.7 Release announcement

src/content/blog/2023-07-24-odh-operator-v2.0-blog.md
=> Add Blog for DataScienceCluster

src/content/blog/2023-07-24-odh-release-1.8.0-blog.md
=> ODH 1.8 release notes

src/content/blog/2023-07-24-odh-release-1.8.0-blog.md
=> Fix link to the Blog

src/content/blog/2023-07-24-odh-operator-v2.0-blog.md
=> Update Installation Guide Link

src/content/blog/2023-07-24-odh-release-1.8.0-blog.md
=> Add KServe to Release notes 1.8

src/content/blog/2023-08-18-trustyai-operator-blog.md
Add the TrustyAI operator blog post announcement.
=> Add TrustyAI operator blog announcement

src/content/blog/2023-08-12-odh-release-1.9.0-blog.md
Announce the ODH 1.9 release of opendatahub
=> Announce ODH 1.9 release

src/content/blog/2023-08-12-odh-release-1.9.0-blog.md
=> Fix typo: an to a

src/content/docs/quick-installation-new-operator.md
It took me quite a while what the word was supposed to be, I was playing with "Flow" but that did not fit.
No testing done.
=> Fixing a typo.

src/content/docs/quick-installation-new-operator.md
The dependencies are needed for the components, not for the DataScienceCluster instance. Let's not complicate steps for setting up the DataScienceCluster instance with something which will only become relevant later.
Fixes https://github.com/opendatahub-io/opendatahub.io/issues/188.
Not tested.
=> The dependencies are needed for the components

src/content/docs/quick-installation-new-operator.md, src/content/docs/quick-installation.md
The 2.X installation instructions are fully standalone, so it makes sense to send the reader to them right at the top.
No testing.
=> The 2.X installation instructions are fully standalone.

src/content/docs/quick-installation-new-operator.md
By default, rolling is selected, so saying to "keep fast" does not match the user experience.
Not tested.
=> By default, rolling is selected.

src/content/docs/quick-installation-new-operator.md, src/content/docs/quick-installation.md
The specific 2.0.0 release seems old news by now, so minimize mentioning it to avoid people looking for it.
No testing.
=> Currently the fast channel has 2.1.0, so 2.0.0 no longer seems available.

src/content/docs/tiered-components.md
Very trivial documentation fix removing unfinished sentence.
=> Trivial documentation fix.

src/content/docs/quick-installation-new-operator.md
With the 2.1.0 operator, the namespace/project is opendatahub, not opendatahub-system.
Not tested.
=> With the 2.1.0 operator, the namespace/project is opendatahub.

src/content/blog/2023-09-26-odh-operator-v2.2-blog.md
ref: https://github.com/opendatahub-io/opendatahub.io/issues/194
=> Docs: add release blog for v2.2

src/content/docs/quick-installation-new-operator.md, src/content/docs/quick-installation.md
Add steps to find the URL of the OpenDataHub Dashboard.
Manually checked the `.md`s at https://github.com/adelton/opendatahub.io/tree/odh-dashboard/src/content/docs.
=> Add steps to find the URL of the OpenDataHub Dashboard.

src/content/docs/quick-installation-new-operator.md, src/content/docs/quick-installation.md
I spent some time trying to find some deeper meaning of the indefinite article and Operators being plural. Other might be confused about it too.
No testing was done.
=> Minimize confusion about the Community Operators being something the user can select (like menu item).

src/content/blog/2023-07-24-odh-operator-v2.0-blog.md, src/content/blog/2023-09-26-odh-release-1.10.0-blog.md
=> Fix Headings for release blog

.github/workflows/deploy-site.yml
This adds build that run everyday at 00:00
Check that cron is formatted correctly
=> deploy on cron

src/const.ts
Edited the src/const.ts file to include two new guide: Managing users and Managing resources
Verified with local build
=> ds-11812 update doc nav bar

src/const.ts
for ODH doc, updated the left nav bar to show lower level heads for the two new guides: Managing users and Managing resources
=> ds-doc-update-nav2

src/content/blog/2023-10-31-odh-release-1.11.0-blog.md
ref: https://github.com/opendatahub-io/opendatahub-community/issues/118
=> Release v1.11.0 / v2.3.0

src/content/blog/2023-11-03-odh-release-2.4.0-blog.md
ref: https://github.com/opendatahub-io/opendatahub-community/issues/138
=> Release: ODH 2.4.0 blog

src/const.ts
Added new "Working with distributed workloads" assembly and updated doc links to use underscores
=> RHOAIENG-6645 Add distributed workloads assembly and update links

src/const.ts
Reorganizing guide content. Created two new guides:
Connecting with accelerators
Working with connected applications
=> rhoai-8238 add two new guides to the toc

src/const.ts
Removing new docs nav menu titles that we added too early.
=> Removing titles added early.

gatsby-config.ts
fixed links for the 2.10 release
=> odh-docs-2.10.1-release

src/components/shared/Layout.tsx, src/components/shared/SideNavigation.tsx
Make it so side navigation TOC expandable items link to section header
click around docs TOC side bar
=> update size nav linking

gatsby-config.ts
Point to documentation for 2.12 release
=> Point to 2.12 docs

gatsby-config.ts
Point to updated documentation in v2.12.1 branch.
=> Point to updated docs for 2.12 release

src/components/shared/Layout.tsx, src/const.ts
- Adding S3 guide to TOC
- Increasing page width to accommodate S3 title
Local build
=> RHOAIENG-11856: TOC updates for S3 guide

gatsby-node.ts, src/pages/docs/index.tsx
=> fix redirect in docs

gatsby-config.ts
Branch update to point to docs for 2.14 release
=> Point to docs for 2.14 release

gatsby-config.ts
Point to documentation for 2.15 release. 
Hi there, This is my first time doing this, I think I have followed instructions, but I am wondering if I should have updated the 'gatsby-config' file 'branch' field in the branch I made, as opposed to the main branch in my repository?
=> Point to documentation for 2.15 release

gatsby-config.ts
Update version for documentation to 2.20
=> Point to documentation for 2.20 release

src/const.ts
Adds a new title to src/const.ts for LAB-tuning content, 16971.
=> New nav menu titles for LAB-tuning and Feature Store

src/content/docs/quick-installation.md
Fix for the spacing of **underODH**
`npm install && npm run develop` and validated in a browser:
=> Minor formatting fix on quick-installation.md
